import type {
    ICredentialType,
    INodeProperties,
} from 'n8n-workflow';

export class Web3 implements ICredentialType {
    name = 'web3wallet';

    displayName = 'Zynd Web3 Wallet';

    properties: INodeProperties[] = [
        {
            displayName: 'Wallet Seed',
            name: 'wallet_seed',
            type: 'string',
            default: '',
            required: true,
            placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            description: 'Autogenerated by Zynd Publisher Node',
            typeOptions: {
                password: true,
            },
        },
        {
            displayName: 'Wallet Address',
            name: 'wallet_address',
            type: 'string',
            default: '',
            required: true,
            placeholder: '0xd5148b96d3fcf3234721c72ec8a57a4b07a45ca3',
            description: 'Autogenerated by Zynd Publisher Node',
        },
    ];
}